### PR TITLE
updates to transport mode

### PR DESCRIPTION
**Pull request by pcppcp**
see readme for updates.

### CODE REVIEW

**Comment by sinosoidal** [comment]
Hey! Sorry for the delay. I will checkout this now.

**Comment by pcppcp** [comment]
Hi guys, do you still want to merge & release these changes? Ableton 10 is out and people report its scripts need update too.

**Comment by jblomster** [comment]
Hi! Sorry for the delay. I've tested this a bit (live 10 + win 10). Nice stuff! We would like to get this merged.

Found two issues that seems to be new with these changes;

1.  Knobs don't work after switching from transport mode. Repro;
- select mixer mode
- turn blue encoder -> selected track level changes
- select transfer mode
- select mixer mode
- turn blue encoder -> nothing happens

If you change track using white keys the track level will work again

2. Arm toggle (7/M1) dont work after changing modes
- select transfer mode
- select mixer mode
- press sel. track arm (7/M1) -> nothing happens

Changing selected track as in issue 1 will fix this
I guess arm toggle should work in all modes?

Is this something you can take a look at perhaps? Do you know if these issues occur in Live 9?

Regarding Live 10: are there any known issues that needs to be fixed for live 10? From what I can see this works fine in Live 10 except the issues above, but I haven't tested it that thoroughly, and I have hardly used it at all in earlier versions of Live.

**Comment by pcppcp** [comment]
Great! Thanks for the heads up. I'll look into the issues you've discovered and will report back once they're fixed.

If the script works with Ableton 10 for you it's great! I thought there were some changes in the API because some people reported that the script wouldn't load for them. I haven't tested it yet myself.

**Pull request closed without merging**
